parser:
  rules: 
    default:
      regex: '^(\w[\w\d-]*):\s*(.*(?:\n\s+.*)*)'
      #regex: '^(\w[\w\d-]*):\s*(.*)$'
      key: 1
      match: 2
    websites:
      regex: '^URL: (.*)$'
      rules:
        url:
          regex: '^(https?://[^\s,]+)'
          group: 1
          match: 1
printer:
  package_table:
    style: 'table'
    columns: all
